#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '[HUSKY] pre commit started'
echo "[HUSKY] run npx eslint 'src/**' --fix"
npx eslint 'src/**' --fix
echo "[HUSKY] run npm run test:staged"
npm run test:staged

# echo '[HUSKY] run npm run pre-commit'
# npx lint-staged --shell
